config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  
  get '/index', to: 'books#index'
  
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
        @reviews = @book.reviews
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
  
<% @books.each do |book| %>
  <div class="book">
    <div class="row">
      <div class="col-md-1">
        <p class="rank-this-week"><%= book.rank_this_week %> </p>
      </div>
      <div class="col-md-9">
        <p class="title"> <%= book.title %>  </p>
        <p class="author">by <%= book.author %>  </p>
        <p class="publisher">(<%= book.publisher %> )</p>
        <p class="description"> <%= book.description %> </p>
        <%= link_to 'See all Editorial Reviews', book_path(book) %>
      </div>
      <div class="col-md-2">
        <p class="weeks-on-list"> <%= book.weeks_on_list %>  weeks on list</p>
      </div>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="book">
  <p class="title"> <%= @book.title %>  </p>
  <p class="author">by <%= @book.author %>  </p>
  <p class="publisher">( <%= @book.publisher %> )</p>
  <p class="description"> <%= @book.description %> </p>
</div>

<div class="reviews">
  <% @reviews.each do |review| %>
    <div class="review">
      <p class="author"> <%= review.author %> </p>
      <p class="comment"> <%= review.comment %> </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <link rel="stylesheet" href="http://content.codecademy.com/projects/bootstrap.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Domine">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Merriweather:300italic,300">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>